export const buildFormData = (data) => {
    const formData = new FormData();

    Object.entries(data).forEach(([key, value]) => {
        if (Array.isArray(value)) {
            value.forEach(v =>
                formData.append(key, v?.originFileObj || v)
            );
        } else {
            formData.append(key, value ?? "");
        }
    });

    return formData;
};

export const NATIONALITIES = [
    { key: "Afghanistan", label: "Afghanistan" },
    { key: "Albania", label: "Albania" },
    { key: "Algeria", label: "Algeria" },
    { key: "Andorra", label: "Andorra" },
    { key: "Angola", label: "Angola" },
    { key: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { key: "Argentina", label: "Argentina" },
    { key: "Armenia", label: "Armenia" },
    { key: "Australia", label: "Australia" },
    { key: "Austria", label: "Austria" },
    { key: "Azerbaijan", label: "Azerbaijan" },
    { key: "Bahamas", label: "Bahamas" },
    { key: "Bahrain", label: "Bahrain" },
    { key: "Bangladesh", label: "Bangladesh" },
    { key: "Barbados", label: "Barbados" },
    { key: "Belarus", label: "Belarus" },
    { key: "Belgium", label: "Belgium" },
    { key: "Belize", label: "Belize" },
    { key: "Benin", label: "Benin" },
    { key: "Bhutan", label: "Bhutan" },
    { key: "Bolivia", label: "Bolivia" },
    { key: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { key: "Botswana", label: "Botswana" },
    { key: "Brazil", label: "Brazil" },
    { key: "Brunei", label: "Brunei" },
    { key: "Bulgaria", label: "Bulgaria" },
    { key: "Burkina Faso", label: "Burkina Faso" },
    { key: "Burundi", label: "Burundi" },
    { key: "Cambodia", label: "Cambodia" },
    { key: "Cameroon", label: "Cameroon" },
    { key: "Canada", label: "Canada" },
    { key: "Central African Republic", label: "Central African Republic" },
    { key: "Chad", label: "Chad" },
    { key: "Chile", label: "Chile" },
    { key: "China", label: "China" },
    { key: "Colombia", label: "Colombia" },
    { key: "Comoros", label: "Comoros" },
    { key: "Congo", label: "Congo" },
    { key: "Costa Rica", label: "Costa Rica" },
    { key: "Croatia", label: "Croatia" },
    { key: "Cuba", label: "Cuba" },
    { key: "Cyprus", label: "Cyprus" },
    { key: "Czech Republic", label: "Czech Republic" },
    { key: "Denmark", label: "Denmark" },
    { key: "Djibouti", label: "Djibouti" },
    { key: "Dominica", label: "Dominica" },
    { key: "Dominican Republic", label: "Dominican Republic" },
    { key: "Ecuador", label: "Ecuador" },
    { key: "Egypt", label: "Egypt" },
    { key: "El Salvador", label: "El Salvador" },
    { key: "Equatorial Guinea", label: "Equatorial Guinea" },
    { key: "Eritrea", label: "Eritrea" },
    { key: "Estonia", label: "Estonia" },
    { key: "Ethiopia", label: "Ethiopia" },
    { key: "Fiji", label: "Fiji" },
    { key: "Finland", label: "Finland" },
    { key: "France", label: "France" },
    { key: "Gabon", label: "Gabon" },
    { key: "Gambia", label: "Gambia" },
    { key: "Georgia", label: "Georgia" },
    { key: "Germany", label: "Germany" },
    { key: "Ghana", label: "Ghana" },
    { key: "Greece", label: "Greece" },
    { key: "Grenada", label: "Grenada" },
    { key: "Guatemala", label: "Guatemala" },
    { key: "Guinea", label: "Guinea" },
    { key: "Guinea-Bissau", label: "Guinea-Bissau" },
    { key: "Guyana", label: "Guyana" },
    { key: "Haiti", label: "Haiti" },
    { key: "Honduras", label: "Honduras" },
    { key: "Hungary", label: "Hungary" },
    { key: "Iceland", label: "Iceland" },
    { key: "India", label: "India" },
    { key: "Indonesia", label: "Indonesia" },
    { key: "Iran", label: "Iran" },
    { key: "Iraq", label: "Iraq" },
    { key: "Ireland", label: "Ireland" },
    { key: "Italy", label: "Italy" },
    { key: "Jamaica", label: "Jamaica" },
    { key: "Japan", label: "Japan" },
    { key: "Jordan", label: "Jordan" },
    { key: "Kazakhstan", label: "Kazakhstan" },
    { key: "Kenya", label: "Kenya" },
    { key: "Kiribati", label: "Kiribati" },
    { key: "Kuwait", label: "Kuwait" },
    { key: "Kyrgyzstan", label: "Kyrgyzstan" },
    { key: "Laos", label: "Laos" },
    { key: "Latvia", label: "Latvia" },
    { key: "Lebanon", label: "Lebanon" },
    { key: "Lesotho", label: "Lesotho" },
    { key: "Liberia", label: "Liberia" },
    { key: "Libya", label: "Libya" },
    { key: "Liechtenstein", label: "Liechtenstein" },
    { key: "Lithuania", label: "Lithuania" },
    { key: "Luxembourg", label: "Luxembourg" },
    { key: "Madagascar", label: "Madagascar" },
    { key: "Malawi", label: "Malawi" },
    { key: "Malaysia", label: "Malaysia" },
    { key: "Maldives", label: "Maldives" },
    { key: "Mali", label: "Mali" },
    { key: "Malta", label: "Malta" },
    { key: "Marshall Islands", label: "Marshall Islands" },
    { key: "Mauritania", label: "Mauritania" },
    { key: "Mauritius", label: "Mauritius" },
    { key: "Mexico", label: "Mexico" },
    { key: "Micronesia", label: "Micronesia" },
    { key: "Moldova", label: "Moldova" },
    { key: "Monaco", label: "Monaco" },
    { key: "Mongolia", label: "Mongolia" },
    { key: "Montenegro", label: "Montenegro" },
    { key: "Morocco", label: "Morocco" },
    { key: "Mozambique", label: "Mozambique" },
    { key: "Myanmar", label: "Myanmar" },
    { key: "Namibia", label: "Namibia" },
    { key: "Nauru", label: "Nauru" },
    { key: "Nepal", label: "Nepal" },
    { key: "Netherlands", label: "Netherlands" },
    { key: "New Zealand", label: "New Zealand" },
    { key: "Nicaragua", label: "Nicaragua" },
    { key: "Niger", label: "Niger" },
    { key: "Nigeria", label: "Nigeria" },
    { key: "North Korea", label: "North Korea" },
    { key: "North Macedonia", label: "North Macedonia" },
    { key: "Norway", label: "Norway" },
    { key: "Oman", label: "Oman" },
    { key: "Pakistan", label: "Pakistan" },
    { key: "Panama", label: "Panama" },
    { key: "Palestine", label: "Palestine" },
    { key: "Papua New Guinea", label: "Papua New Guinea" },
    { key: "Paraguay", label: "Paraguay" },
    { key: "Peru", label: "Peru" },
    { key: "Philippines", label: "Philippines" },
    { key: "Poland", label: "Poland" },
    { key: "Portugal", label: "Portugal" },
    { key: "Qatar", label: "Qatar" },
    { key: "Romania", label: "Romania" },
    { key: "Russia", label: "Russia" },
    { key: "Rwanda", label: "Rwanda" },
    { key: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { key: "Saint Lucia", label: "Saint Lucia" },
    { key: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
    { key: "Samoa", label: "Samoa" },
    { key: "San Marino", label: "San Marino" },
    { key: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { key: "Saudi Arabia", label: "Saudi Arabia" },
    { key: "Senegal", label: "Senegal" },
    { key: "Serbia", label: "Serbia" },
    { key: "Seychelles", label: "Seychelles" },
    { key: "Sierra Leone", label: "Sierra Leone" },
    { key: "Singapore", label: "Singapore" },
    { key: "Slovakia", label: "Slovakia" },
    { key: "Slovenia", label: "Slovenia" },
    { key: "Solomon Islands", label: "Solomon Islands" },
    { key: "Somalia", label: "Somalia" },
    { key: "South Africa", label: "South Africa" },
    { key: "South Korea", label: "South Korea" },
    { key: "South Sudan", label: "South Sudan" },
    { key: "Spain", label: "Spain" },
    { key: "Sri Lanka", label: "Sri Lanka" },
    { key: "Sudan", label: "Sudan" },
    { key: "Suriname", label: "Suriname" },
    { key: "Sweden", label: "Sweden" },
    { key: "Switzerland", label: "Switzerland" },
    { key: "Syria", label: "Syria" },
    { key: "Taiwan", label: "Taiwan" },
    { key: "Tajikistan", label: "Tajikistan" },
    { key: "Tanzania", label: "Tanzania" },
    { key: "Thailand", label: "Thailand" },
    { key: "Timor-Leste", label: "Timor-Leste" },
    { key: "Togo", label: "Togo" },
    { key: "Tonga", label: "Tonga" },
    { key: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { key: "Tunisia", label: "Tunisia" },
    { key: "Turkey", label: "Turkey" },
    { key: "Turkmenistan", label: "Turkmenistan" },
    { key: "Tuvalu", label: "Tuvalu" },
    { key: "Uganda", label: "Uganda" },
    { key: "Ukraine", label: "Ukraine" },
    { key: "United Arab Emirates", label: "United Arab Emirates" },
    { key: "United Kingdom", label: "United Kingdom" },
    { key: "United States", label: "United States" },
    { key: "Uruguay", label: "Uruguay" },
    { key: "Uzbekistan", label: "Uzbekistan" },
    { key: "Vanuatu", label: "Vanuatu" },
    { key: "Vatican City", label: "Vatican City" },
    { key: "Venezuela", label: "Venezuela" },
    { key: "Vietnam", label: "Vietnam" },
    { key: "Yemen", label: "Yemen" },
    { key: "Zambia", label: "Zambia" },
    { key: "Zimbabwe", label: "Zimbabwe" }
];

export const sortNationalitiesBySearch = (list, searchText) => {
    if (!searchText) return list;

    const text = searchText.toLowerCase();

    const startsWith = [];
    const contains = [];

    list.forEach((item) => {
        const label = item.label.toLowerCase();

        if (label.startsWith(text)) {
            startsWith.push(item);
        } else if (label.includes(text)) {
            contains.push(item);
        }
    });

    return [...startsWith, ...contains];
};