const APP_POLICY = {
  GET_APP_POLICIES: "GET_APP_POLICIES",
  GET_APP_POLICY_BY_ID: "GET_APP_POLICY_BY_ID",

  CREATE_APP_POLICY: "CREATE_APP_POLICY",
  UPDATE_APP_POLICY: "UPDATE_APP_POLICY",

  DEACTIVATE_APP_POLICY: "DEACTIVATE_APP_POLICY",
};

export default APP_POLICY;