const NOTIFICATION = {

  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',

  MARK_AS_READ: 'MARK_AS_READ',

  MARK_ALL_AS_READ: 'MARK_ALL_AS_READ',

  NEW_NOTIFICATION_RECEIVED: 'NEW_NOTIFICATION_RECEIVED',

};

export default NOTIFICATION;