const TASK_CONSTANT = {

    CREATE_TASK: 'CREATE_TASK',

    GET_USER_TASK: 'GET_USER_TASK',

    GET_TASK_LIST_BY_STATUS: 'GET_TASK_LIST_BY_STATUS',

    GET_TASK_DETAIL: 'GET_TASK_DETAIL',

    SUBMIT_FOR_REVIEW: 'SUBMIT_FOR_REVIEW',

    MARK_AS_CLOSED: 'MARK_AS_CLOSED',

    ASSIGN_TASK_TO_EMPLOYEE: 'ASSIGN_TASK_TO_EMPLOYEE',

    GET_COMMENTS: 'GET_COMMENTS',

    ADD_COMMENTS: 'ADD_COMMENTS',

    SET_STATUS: 'SET_STATUS',

    FORWARD_ONBOARDING_TASK: 'FORWARD_ONBOARDING_TASK',

    CREATE_RESIGNATION_REQUEST: 'CREATE_RESIGNATION_REQUEST',

    FORWARD_OFFBOARDING_TASK: 'FORWARD_OFFBOARDING_TASK',

    COUNTER_OFFER: 'COUNTER_OFFER',

    RESPOND_COUNTER_OFFER: "RESPOND_COUNTER_OFFER",

    EDIT_TASK: 'EDIT_TASK',

    TASK_UPSERT_SOCKET: 'TASK_UPSERT_SOCKET',
    TASK_REMOVE_SOCKET: 'TASK_REMOVE_SOCKET',

};

export default TASK_CONSTANT